export const PRICING_OPTIONS = {
	// Individual Plans
	INDIVIDUAL: {
		BASIC: 350,
		ADVANCED: 500,
		PREMIER: 750,
		ADD_ONS: {
			ADDITIONAL_SCHEDULE_C: 150,
			ADDITIONAL_K_1: 125,
			ADDITIONAL_BROKERAGE_ACCOUNT: 50,
			ADDITIONAL_STATE: 150,
			ADDITIONAL_RENTAL: 150,
			CRYPTO_SUMMARY: 300,
		},
	},
	BUSINESS: {
		FORMATION: {
			LLC_EIN: 600,
			ENTITY_ELECTION: 300,
			STATE_COMPLIANCE: 300,
			REGISTERED_AGENT: 200,
		},
		BOOKKEEPING: {
			STARTER: 350,
			CORE: 600,
			GROWTH: 1000,
			CLEANUP_PROJECT: 2000,
			ACCOUNT_SETUP: 500,
		},
		PAYROLL: {
			SETUP: 200,
			MONTHLY_ADMIN: 100,
			EMPLOYEE_PAY: 10,
			FORM_GENERATE: 15,
		},
		TAX_PREPARATION: {
			PARTNERSHIP_SIMPLE: 1200,
			PARTNERSHIP_STANDARD: 1800,
			C_CORP_STANDARD: 2000,
		},
		ADD_ONS: {
			FRANCHISE_TAX_REPORT: 200,
			MULTI_STATE_APPORTIONMENT: 200,
			ADDITIONAL_K_1: 100,
		},
	},
	RETIREMENT: {
		PLANNING_HOURLY_RATE: 200,
	},
};

export const POLICIES = {
	LAST_UPDATED: 'October 10th, 2025',
	DOMAIN: 'www.itmtax.com',
	COMPANY_NAME: 'ITM Tax & Advisory, LLC',
	EMAIL: 'info@itmtax.com',
	PHONE: '+1 (346) 475-5148',
	ADDRESS: 'Missouri City, TX 77459',
};
